[parser]
min_price = 500
max_price = 700
max_square = 9999
min_square = 35

[driver]
firefox_binary = "/opt/waterfox/waterfox"
geckodriver = "/usr/bin/geckodriver"

[directories]
save = "data"

[database]
dbname = "flats"
user = "admin"
