name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint selenium openpyxl
    - name: Analysing the code with pylint
      run: |
        PYTHONPATH=.venv/lib/python3.13/site-packages pylint --fail-under=9 $(git ls-files '*.py')
